#!/bin/bash

data_size=600000

cd tests

for i in bigtest-*.lua; do 
	echo
	echo '***' $i '***'
	echo
        (
            ulimit -c 0 
            ulimit -d $data_size
            ulimit -v $data_size
            ../ocroscript  -e '
                ok,result = pcall(function() dofile("'$i'") end)
                if not ok then print(result.." TEST FAILED UNEXPECTEDLY ('$i')") end
            ' /dev/null || {
                echo "ocroscript exited.  It probably was trying to use too much memory."
                echo "The limits for bigtests are:"
                echo
                echo "data_size=$data_size kbytes"
                echo
                ulimit -a
            }
        )
done
