#!/bin/bash

#
# makes sure that ocropus compiles !
#
# Responsible: kofler
#

# include common functions (look there for documentation!)
. `dirname $0`/common.sh

# make sure we are in the right directory
verifyDir

retvalue=0

section RUN-TESTS
for test in `ls */test-* | grep -v "\." | grep -v test-list | grep -v testing/`; do
    verifyCommand "$test" 0
    if [ $? -ne 0 ]; then
        retvalue=$((retvalue + 1))
    fi
done

exit $retvalue
