#!/bin/bash

#
# makes sure that ocropus compiles !
#
# Responsible: kofler
#

# include common functions (look there for documentation!)
. `dirname $0`/common.sh

# make sure we are in the right directory
verifyDir

retvalue=0

section TEST-COMPILE
# actually build ocropus
verifyCommand "./configure" 0
if [ $? -ne 0 ]; then
    retvalue=$((retvalue + 1))
fi
jam clean
verifyCommand "jam -q" 0
if [ $? -ne 0 ]; then
    retvalue=$((retvalue + 1))
fi
verifyCommand "test -x ocrocmd/ocrocmd" 0
if [ $? -ne 0 ]; then
    retvalue=$((retvalue + 1))
fi
exit $retvalue
