#! /usr/bin/perl -w
use strict;
use warnings;
use Test::More 'no_plan';
binmode STDOUT, ":utf8";
use utf8;
use String::Approx 'amatch';
use lib '../..';
use Cwd 'abs_path';
use Converter;
use Extractor;
my %cfg = do 'config.pl';

my %tests = (

 '/home/wo/programming/opp-tools/test/doctests/11-Byrne-Hayek-Hume.pdf' => "David Lewis claims that a simple sort of anti-Humeanism—that the rational agent desires something to the extent he believes it to be good—can be given a decision-theoretic formulation, which Lewis calls “Desire as Belief” (DAB). Given the (widely held) assumption that Jeffrey conditionalising is a rationally permissible way to change one’s mind in the face of new evidence, Lewis proves that DAB leads to absurdity. Thus, according to Lewis, the simple form of anti-Humeanism stands refuted. In this paper we investigate whether Lewis’s case against DAB can be strengthened by examining how it fares under rival versions of decision theory, including other conceptions of rational ways to change one’s mind. We prove a stronger version of Lewis’s result in “Desire as Belief II”. We then argue that the anti-Humean may escape Lewis’s argument either by adopting a version of causal decision theory, or by claiming that the refutation only applies to hyper-idealised rational agents, or by denying that the decision-theoretic framework has the expressive capacity to formulate anti-Humean-ism.",

 '/home/wo/programming/opp-tools/test/doctests/11-Incurvati-Smith-Rejection.pdf' => "Timothy Smiley’s wonderful paper ‘Rejection’ (1996) is still perhaps not as well known or well understood as it should be. This note first gives a quick presentation of themes from that paper, though done in our own way, and then considers a putative line of objection – recently advanced by Julien Murzi and Ole Hjortland (2009) – to one of Smiley’s key claims. Along the way, we consider the prospects for an intuitionistic approach to some of the issues discussed in Smiley’s paper.",

 '/home/wo/programming/opp-tools/test/doctests/11-Rayo-Generality.pdf' => "Years ago, when I was young and reckless, I believed that there was such a thing as an all-inclusive domain. Now I have come to see the error of my ways. The source of my mistake was a view that might be labeled ‘Tractarianism’. Tractarians believe that language is subject to a metaphysical constraint. In order for an atomic sentence to be true, there needs to be a certain kind of correspondence between the semantic structure of the sentence and the ‘metaphysical structure of reality’. More specifically, Tractarianism is the conjunction of the following three claims: 1. there is a particular carving of reality into objects which is more apt, in some metaphysical sense, than any potential rival—the one and only carving that is in accord with reality’s true metaphysical structure; 2. to each legitimate singular term there must correspond an object carved out by this metaphysical structure; and 3. satisfaction of the truth-conditions of an atomic sentence of the form <i>P</i> (<i>t</i><sub>1</sub><i>, . . . , t</i><sub><i>n</i></sub>) requires that the objects paired with <i>t</i><sub>1</sub><i>, . . . , t</i><sub><i>n</i></sub> bear to each other the property expressed by <i>P</i> .",

 '/home/wo/programming/opp-tools/test/doctests/11-Skyrms-Game.pdf' => "Game theory based on rational choice is compared with game theory based on evolutionary, or other adaptive, dynamics. The Nash equilibrium concept has a central role to play in both theories, even though one makes extremely strong assumptions about cognitive capacities and common knowledge of the players, and the other does not. Nevertheless, there are also important differences between the two theories. These differences are illustrated in a number of games that model types of interaction that are key ingredients for any theory of the social contract.",

 '/home/wo/programming/opp-tools/test/doctests/22-Anon-Ramsey.pdf' => "According to the Ramsey Test, a person should accept a conditional to the extent that she would accept the consequent on the supposition that the antecedent is true. There are two apparently attractive ways of interpreting the Ramsey test: one probabilistic, and the other in terms of truth conditions and possible worlds. Unfortunately, these two interpretations are difficult to combine due to a set of triviality results. The difficulty remains even when the probabilistic interpretation is adjusted to allow for “local” as well as a “global” readings of certain conditionals. I suggest that both readings of the Ramsey Test can be usefully combined using two philosophical tools. The first of these tools is the assignment of intermediate truth values to counterfactuals. The second is the concept of a general imaging function proposed by Gärdenfors [1982].",

 '/home/wo/programming/opp-tools/test/doctests/21-Polger-Shapiro-Understanding.pdf' => "Carl Gillett has defended what he calls the “dimensioned” view of the realization relation, which he contrasts with the traditional “flat” view of realization (2003, 2007; see also Gillett 2002). Intuitively, the dimensioned approach characterizes realization in terms of composition whereas the flat approach views realization in terms of occupiers of functional roles. Elsewhere we have argued that the general view of realization and multiple realization that Gillett advances is not able to discharge the theoretical duties of those relations (Shapiro 2004, unpublished manuscript; Polger 2004, 2007, forthcoming). Here we focus on an internal objection to Gillett’s account and then raise some broader reasons to reject it.",

 '/home/wo/programming/opp-tools/test/doctests/22-Evans-Pronouns.pdf' => "Some philosophers, notably Professors Quine and Geach, have stressed the analogies they see between pronouns of the vernacular and the bound variables of quantification theory, Geach, indeed, once maintained that 'for a philosophical theory of reference, then, it is all one whether we consider bound variables or pronouns of the vernacular'.\" This slightly overstates Ceach's positition since he recognizes that some pronouns of ordinary language do function differently from bound variables; he calls such pronouns 'pronouns of laziness'. Ceach's characterisation of pronouns of laziness has varied from time to time, but the general idea should be clear from a paradigm example: (1) A man who sometimes beats his wife has more sense than one who always gives in to her.",

 '/home/wo/programming/opp-tools/test/doctests/22-Fricker-Understanding.pdf' => "When a human speaker-hearer of a language hears and understands an utterance by another speaker of a sentence of their shared language, she typically comes to know, or comes to be in a position to know, what speech act was effected in the utterance. But her forming of a knowledgeable belief about what was said is not the most immediate psychological upshot of her auditing of the utterance. In fact she may not, as it were, bother to form a belief about what was said at all. The most immediate personal-level psychological effect of her auditing of the utterance is that she enjoys a representation of a distinctive kind special to language understanding: a conscious representation of the content and force of the utterance. She hears the utterance not merely as sound, but as the speech act that it is. This representation of meaning is not phenomenologically distinct from her hearing of the sounds. She hears its meaning in the utterance itself, experiences it as a semantically laden event. It is for her as if, in perceiving the utterance, she perceives not just the sounds, but equally perceives their meaning. It is a fact of phenomenology that we enjoy such understanding-experiences, quasi-perceptions of meaning.",

 '/home/wo/programming/opp-tools/test/doctests/22-Kolodny-Myth.pdf' => "It is often said that there is a special class of norms, ‘rational requirements’, that demand that our attitudes be related one another in certain ways, whatever else may be the case. In recent work, a special class of these rational requirements has attracted particular attention: what I will call ‘requirements of formal coherence as such’, which require just that our attitudes be formally coherent. For example, we are rationally required, if we believe something, to believe what it entails. And we are rationally required, if we intend an end, to intend what we take to be necessary means to it. The intuitive idea is that formally incoherent attitudes give rise to a certain normative tension, or exert a kind of rational pressure on each another, and this tension, or pressure, is relieved just when one of the attitudes is revised. As John Broome observes, these requirements are, by their nature, ‘wide scope’, which is to say that there is no particular attitude that one must have or lack in order to satisfy them. This is because they require just formal coherence, and there is no particular attitude that one must have or lack in order to be formally coherent.",

 '/home/wo/programming/opp-tools/test/doctests/22-Block-Anna.pdf' => "The Anna Karenina theory says: all conscious states are alike; each unconscious state is unconscious in its own way. This paper argues that many components have to function properly to produce consciousness, but failure in any one of many different ones can yield an unconscious state in different ways. In that sense the Anna Karenina theory is true. But in another respect it is false: kinds of unconsciousness depend on kinds of consciousness.",

 '/home/wo/programming/opp-tools/test/doctests/32-Block-Functional.pdf' => "A critique of the functional reduction picture of reductive explanation, a picture shared by proponents such as Lewis and opponents such as Kim, Chalmers and Jackson.",

 '/home/wo/programming/opp-tools/test/doctests/21-Anon-Qualia.pdf' => "Qualia include the ways things look, sound and smell, the way it feels to have a pain; more generally, what it's like to have mental states. Qualia are experiential properties of sensations, feelings, perceptions and, in my view, thoughts and desires as well. But, so defined, who could deny that qualia exist? Yet, the existence of qualia is controversial. Here is what is controversial: whether qualia, so defined, can be characterized in intentional, functional or purely cognitive terms. Opponents of qualia think that the content of experience is intentional content (like the content of thought), or that experiences are functionally definable, or that to have a qualitative state is to have a state that is monitored in a certain way or accompanied by a thought to the effect that I have that state. If we include the idea that experiential properties are not intentional or functional or purely cognitive in the definition of `qualia', then it is controversial whether there are qualia.",

 '/home/wo/programming/opp-tools/test/doctests/222-Solt-Measurement.pdf' => "This paper presents corpus data illustrating a range of previously unnoticed distributional and interpretive differences between the superficially equivalent quantifiers <i>most</i> and <i>more than half</i>. It is shown that all of them derive from a basic difference in logical form (per Hackl 2009), which places different requirements on the structure of the underlying measurement scale: <i>more than half</i> must be interpreted relative to a ratio scale, while <i>most</i> can be interpreted relative to an ordinal or semi-ordered scale, the latter parallel in structure to the leading psychological model of humans’ approximate numerical abilities. These results demonstrate the relevance of measurement theoretic concepts to natural language meaning, and point in particular to the conclusion that the grammar includes measurement scales whose points are not totally ordered with respect to one another. This case study also illustrates a close link between the semantics of quantitificational expressions on the one hand and the cognitive representation of quantity and measure on the other.",

 '/home/wo/programming/opp-tools/test/doctests/33-Lange-Einstein.pdf' => "Einstein is widely understood as regarding “principle theories” (such as the theory of relativity) as explanatorily powerless. This brief paper shows that Einstein’s remarks admit of another interpretation, according to which principle theories possess explanatory power. This interpretation is motivated primarily by showing that James Jeans made remarks very similar to Einstein’s at nearly the same time, but Jeans reconciled those remarks with holding principle theories to be explanatory. Einstein’s remarks could well be getting at the same point as Jeans’s. This view of principle and constructive theories is independently valuable. It undermines Salmon’s “friendly physicist” example as an argument for the view that there are facts that can be explained by both principle and constructive theories.",

 '/home/wo/programming/opp-tools/test/doctests/AB-Grundmann-Thought.pdf' => "Descriptions of Gettier cases can be interpreted in ways that are incompatible with the standard judgment that they are cases of justified true belief without knowledge. Timothy Williamson claims that this problem cannot be avoided by adding further stipulations to the case descriptions. To the contrary, we argue that there is a fairly simple way to amend the Ford case, a standard description of a Gettier case, in such a manner that all deviant interpretations are ruled out. This removes one major objection to interpreting our judgments about Gettier cases as strict conditionals.",

 '/home/wo/programming/opp-tools/test/doctests/AB-McAnich-Animal.pdf' => "One of the earliest issues in cognitive ethology concerned the meaning of animal signals. In the 1970s and 1980s this debate was most active with respect to the question of whether animal alarm calls convey information about the emotional states of animals or whether they “refer” directly to predators in the environment (Seyfarth, Cheney, &amp; Marler 1980; see Radick 2007 for a historical account), but other areas, such as vocalizations about food and social contact, were also widely discussed. In the 1990s, ethologists largely came to a consensus that such calls were “functionally referential” (Evans &amp; Marler 1995) even if they did not satisfy all the semantic requirements imposed by philosophers of language. More recently, though, it has been argued that ethologists should eschew the concept of reference and return to a focus on the affective aspects of animal communication (Rendall &amp; Owren 2002). We propose to take a new look at this debate in the light of recent developments in the philosophy of language under the heading of “Neo-Expressivism” (Bar-On 2004). This view provides two different senses in which an utterance satisfies an <i>expressive</i> function. We intend to use Neo- Expressivism to provide a philosophical framework for understanding the relationship between the affective and referential aspects of animal signals by seeing them as <i>both</i>  acts that express some motivational state of the animal <i>and</i> products that express propositions with truth-evaluable content. Defending the second part of this claim requires us to reject the recent proposal that non-conceptual content is entirely adequate for understanding the cognition and communication of animals.",

 '/home/wo/programming/opp-tools/test/doctests/22-Weisberg-Structure.pdf' => "Despite their best efforts, scientists may be unable to construct models that simultaneously exemplify every theoretical virtue. One explanation for this is the existence of tradeoffs: relationships of attenuation that constrain the extent to which models can have such desirable qualities. In this paper, we characterize three types of tradeoffs theorists may confront. These characterizations are then used to examine the relationships between parameter precision and several types of generality. We show that several of these relationships exhibit tradeoffs and discuss what consequences those tradeoffs have for theoretical practice.",

 '/home/wo/programming/opp-tools/test/doctests/AB2-Balcerak-Reasoning.pdf' => "In this essay we argue that reasoning can sometimes generate epistemic justification, rather than merely transmitting justification that the subject already possesses to new beliefs. We also suggest a way to account for it in terms of the relationship between epistemic normative requirements, justification and cognitive capacities.",

 '/home/wo/programming/opp-tools/test/doctests/AB2Schoubye-What.pdf' => "It is sometimes argued that certain sentences of natural language fail to express truth conditional contents. Standard examples include e.g. Tipper is ready and Steel is strong enough. In this paper, we provide a novel analysis of truth conditional meaning (what is said) using the notion of a question under discussion. This account (i) explains why these types of sentences are not, in fact, semantically underdetermined (yet seem truth conditionally incomplete), (ii) provides a principled analysis of the process by which natural language sentences (in general) can come to have enriched meanings in context, and (iii) shows why various alternative views, e.g. so-called Radical Contextualism, Moderate Contextualism, and Semantic Minimalism, are partially right in their respective analyses of the problem, but also all ultimately wrong. Our analysis achieves this result using a standard truth conditional and compositional semantics and without making any assumptions about enriched logical forms, i.e. logical forms containing phonologically null expressions.",

 '/home/wo/programming/opp-tools/test/doctests/bradleyan-regresses-eds-hochberg-mulligan.pdf' => "Old English manors have their ghosts. And though I would not want to call analytic philosophy a ‘manor’, nor exactly ‘old’, it certainly is of some decent English origin, and it left adolescence a while ago. No wonder then, that it is not exempt from haunting terrors. One particular spectre has been haunting it for decades; it already gave some analytic pioneers the creeps, and we still now and then find people terrified by it: the ghost of old Bradley has not yet found its rest and keeps on threatening people with his notorious regress. The present essay is a lecture in exorcism; much of the fear old Bradley spread, so I will argue, peters out once we dare to look it in the eye.",

 '/home/wo/programming/opp-tools/test/doctests/23-Badgaiyan-Priming.pdf' => "Neuroimaging studies suggest that within-modality priming is associated with reduced regional cerebral blood flow (rCBF) in the extrastriate area, whereas cross-modality priming is associated with increased rCBF in prefrontal cortex. To characterize the nature of rCBF changes in within- and cross-modality priming, we conducted two neuroimaging experiments using positron emission tomography (PET). In experiment 1, rCBF changes in within-modality auditory priming on a word stem completion task were observed under same- and different-voice conditions.",

 '/home/wo/programming/opp-tools/test/doctests/333-Heng-et-al-Glutan.pdf' => "The expressions of reference genes used in gene expression studies are assumed to be stable under most circumstances. However, a number of studies had demonstrated that such genes were found to vary under experimental conditions. In addition, genes that are stably expressed in an organ may not be stably expressed in other organs or other organisms, suggesting the need to identify reference genes for each organ and organism. This study aims at identifying stably expressed genes in <i>Escherichia coli</i>. Microarray datasets from <i>E. coli</i> substrain MG1655 and 1 dataset from W3110 were analysed. Coefficient of variance (COV) of was calculated and 10% of the lowest COV from 4631 genes common in the 3 MG1655 sets were analysed using NormFinder. Glucan biosynthesis protein G (<i>mdoG</i>), which is involved in cell wall synthesis, displayed the lowest weighted COV and weighted NormFinder Stability Index for the MG1655 datasets, while also showing to be the most stable in the dataset for substrain W3110, suggesting that <i>mdoG</i> is a suitable reference gene for <i>E. coli</i> K-12. Gene ontology over-representation analysis on the 39 genes suggested an over-representation of cell division, carbohydrate metabolism, and protein synthesis which supports the short generation time of <i>E. coli</i>.",



);

sub proc {
    my $file = shift;
    convert2xml($file);
    my $extractor = Extractor->new("$file.xml");
    $extractor->extract('abstract');
    system("rm $file.xml");
    return $extractor->{abstract};
}

while (my ($file, $res) = each(%tests)) {
    print substr($file, length('/home/wo/programming/opp-tools/test/doctests/')), "\n";
    my $abs;
    eval {
        $abs = proc($file);
    };
    next if ($@);
    is($abs, $res);
}
