image = bytearray:new()
read_image_gray(image,"images/simple.png")
make_page_black(image)
dinit(800,800)
dshow(image,"x")
read_image_gray(image,"images/twocol.png")
make_page_black(image)
dshow(image,"d")
dwait()
