function show(pix,where)
    where = where or ""
    a = bytearray:new()
    lepton.as_array(a,pix)
    dshow(a,where)
    a:delete()
end

dinit(800,800)
pixs = lepton.pixRead("images/dave-start.png")
show(pixs,"a")
pix1 = lepton.pixThresholdToBinary(pixs,240)
show(pix1,"b")
val,angle,conf = lepton.pixFindSkew(pix1,0,0)
note(angle,conf)
pix2 = lepton.pixRotateAMGray(pixs,angle*M_PI/180,0)
show(pix2,"c")
pix3 = lepton.pixCloseGray(pix2,51,lepton.L_HORIZ)
pix4 = lepton.pixErodeGray(pix3,5,lepton.L_VERT)
pix5 = lepton.pixThresholdToBinary(pix4,230)
show(pix5,"d")
dwait()
